# Manually started action to build Python for Apple ARM Mac and upload to an artifact

name: Build ARM Python3 for Mac
on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
    paths-ignore:
    - '.github/**' # Ignore changes towards the .github directory

jobs:
  build:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.3.1'

    - name: Build Python3
      run: |
        uname -a
        brew update
        brew install bash libtool automake

        wget https://www.python.org/ftp/python/3.12.2/Python-3.12.2.tar.xz
        tar xvf Python-3.12.2.tar.xz
        cd Python-3.12.2

        # Allow relative prefixes
        grep -v "expected an absolute directory name" configure > configure.patched
        chmod +x ./configure.patched

        # Build!
        ./configure.patched --prefix=.
        make -j
        make install

        # Make real tree
        mkdir python3
        mv bin/python3.12 python3/python3
        mv include lib share python3/.
        tar cvf /tmp/python3.12-portable-darwin_arm64.tar python3

    - name: Upload Python3-ARM
      uses: actions/upload-artifact@v4
      with:
        name: python3.12-portable-darwin_arm64.tar
        path: /tmp/python3.12-portable-darwin_arm64.tar

    - name: Download built binaries
      uses: actions/download-artifact@v4

    - name: Release
      uses: jason2866/action-gh-release@v1.3
      if: startsWith(github.ref, 'refs/tags/')
      with:
        prerelease: false
        files: |
          *.tar
      env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
